services:
  - type: web
    name: agentic-ai-service
    env: python
    runtime: python3
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: OPENAI_API_KEY
        sync: false